version: '3'
services:
  vtp:
    build: .
    networks:
      default:
        aliases:
          - vtp
    ports:
      - 8060:8060 # HTTP
      - 8389:8389 # LDAP
    environment:
      - DISABLE_SSL=true
    volumes:
      - "~/.modig/:/root/.modig"
